// Generated from internal/invoicefields by: go test ./internal/invoicefields -run TestInvoiceFields_TheSPAFileIsGeneratedFromTheList -update
export const INVOICE_FIELDS = [
  {
    "key": "invoice_number",
    "label": "Invoice number",
    "type": "text",
    "line": false,
    "importKey": "invoice_number",
    "required": true,
    "formKey": "number",
    "edit": false,
    "extract": true
  },
  {
    "key": "issue_date",
    "label": "Issue date",
    "type": "date",
    "line": false,
    "importKey": "issue_date",
    "required": false,
    "formKey": "date",
    "edit": true,
    "extract": true
  },
  {
    "key": "supplier_tin",
    "label": "Supplier TIN",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "supplier_name",
    "label": "Supplier name",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "buyer_tin",
    "label": "Buyer TIN",
    "type": "text",
    "line": false,
    "importKey": "buyer_tin",
    "required": false,
    "formKey": "buyerTin",
    "edit": true,
    "extract": true
  },
  {
    "key": "buyer_name",
    "label": "Buyer name",
    "type": "text",
    "line": false,
    "importKey": "buyer_name",
    "required": false,
    "formKey": "buyer",
    "edit": true,
    "extract": true
  },
  {
    "key": "currency",
    "label": "Currency",
    "type": "text",
    "line": false,
    "importKey": "currency",
    "required": false,
    "formKey": "currency",
    "edit": true,
    "extract": true
  },
  {
    "key": "subtotal",
    "label": "Subtotal",
    "type": "money",
    "line": false,
    "importKey": "subtotal",
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "vat",
    "label": "VAT",
    "type": "money",
    "line": false,
    "importKey": "vat",
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "total",
    "label": "Total",
    "type": "money",
    "line": false,
    "importKey": "total",
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "invoice_kind",
    "label": "Invoice kind",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "tax_currency_code",
    "label": "Tax currency code",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "due_date",
    "label": "Due date",
    "type": "date",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "issue_time",
    "label": "Issue time",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "tax_point_date",
    "label": "Tax point date",
    "type": "date",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "payment_status",
    "label": "Payment status",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "supplier_email",
    "label": "Supplier email",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "supplier_telephone",
    "label": "Supplier telephone",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "supplier_street",
    "label": "Supplier street",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "supplier_city",
    "label": "Supplier city",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "supplier_postal_zone",
    "label": "Supplier postal zone",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "supplier_country",
    "label": "Supplier country",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "supplier_state",
    "label": "Supplier state",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "supplier_lga",
    "label": "Supplier LGA",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "buyer_email",
    "label": "Buyer email",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "buyer_telephone",
    "label": "Buyer telephone",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "buyer_street",
    "label": "Buyer street",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "buyer_city",
    "label": "Buyer city",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "buyer_postal_zone",
    "label": "Buyer postal zone",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "buyer_country",
    "label": "Buyer country",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "buyer_state",
    "label": "Buyer state",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "buyer_lga",
    "label": "Buyer LGA",
    "type": "text",
    "line": false,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "description",
    "label": "Description",
    "type": "text",
    "line": true,
    "importKey": "line_description",
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "quantity",
    "label": "Quantity",
    "type": "quantity",
    "line": true,
    "importKey": "line_quantity",
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "unit_price",
    "label": "Unit price",
    "type": "money",
    "line": true,
    "importKey": "line_unit_price",
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "line_total",
    "label": "Line total",
    "type": "money",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "line_tax",
    "label": "Line tax",
    "type": "money",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": true,
    "extract": true
  },
  {
    "key": "tax_category",
    "label": "Tax category",
    "type": "text",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "hsn_code",
    "label": "HSN code",
    "type": "text",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "isic_code",
    "label": "ISIC code",
    "type": "text",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "product_category",
    "label": "Product category",
    "type": "text",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "service_category",
    "label": "Service category",
    "type": "text",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "sellers_item_identification",
    "label": "Seller's item identification",
    "type": "text",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "price_unit",
    "label": "Price unit",
    "type": "text",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "tax_percent",
    "label": "Tax percent",
    "type": "money",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  },
  {
    "key": "base_quantity",
    "label": "Base quantity",
    "type": "quantity",
    "line": true,
    "importKey": null,
    "required": false,
    "formKey": null,
    "edit": false,
    "extract": false
  }
] as const
