#!/bin/bash
# PreCompact hook - saves session state before compaction.
# Writes to .claude/handoff.yaml relative to the CWD, so when Claude is
# running inside a RALPH story worktree, the handoff stays scoped to that
# worktree (see RALPH_PROMPT.md § Session Continuity).
#
# If the handoff already exists (Claude updated it during work), preserve
# the populated fields and only refresh the timestamp + trigger. Otherwise
# write a fresh template.

HANDOFF_FILE=".claude/handoff.yaml"
TIMESTAMP=$(date -Iseconds)

mkdir -p "$(dirname "$HANDOFF_FILE")"

if [ -f "$HANDOFF_FILE" ]; then
  # Preserve existing state - update only timestamp + trigger.
  # -i.bak is portable across BSD (macOS) and GNU sed; the .bak is removed below.
  sed -i.bak \
    -e "s|^# Auto-generated by PreCompact hook at: .*|# Auto-generated by PreCompact hook at: $TIMESTAMP|" \
    -e "s|^timestamp: .*|timestamp: \"$TIMESTAMP\"|" \
    -e "s|^trigger: .*|trigger: \"pre-compact\"|" \
    "$HANDOFF_FILE"
  rm -f "$HANDOFF_FILE.bak"
  echo "PreCompact: Refreshed timestamp in existing $HANDOFF_FILE (preserved state)"
else
  # First-run template
  cat > "$HANDOFF_FILE" << EOF
# Auto-generated by PreCompact hook at: $TIMESTAMP
# Claude: READ THIS FILE to restore session context

timestamp: "$TIMESTAMP"
trigger: "pre-compact"
workflow: ralph

# Session state (populated by Claude during work)
story_id: null
current_subtask: null
stage: null  # architecture|explore|test-spec|execution|qa-verify|deploy-gate
completed_subtasks: []

progress: |
  Session was compacted. Check Backlog for subtask details
  via mcp__backlog__task_list (labels: ["story:<slug>"]) / mcp__backlog__task_view.

decisions: []
blockers: []

branch: null
worktree_path: null
pr_number: null

# IMPORTANT: After reading this file, query Backlog for full subtask context.
EOF
  echo "PreCompact: Created new $HANDOFF_FILE"
fi
