// Row shape for the Workspace atom-drift guard (App.atomAudit.test.tsx). AUDITED_ATOMS
// itself -- the 38-row audit table -- is authored next; this file only fixes its shape.

export type Verdict = 'stale-and-reachable' | 'stale-but-unreachable' | 'correctly-reset' | 'deliberate'

export type AuditedAtom = {
  // Verbatim text extracted by the two regexes in App.atomAudit.test.tsx: an
  // `[x, setX]` pair for a useState atom, or the bare name for reqInFlight (useRef).
  binding: string
  name: string
  line: number
  kind: 'useState' | 'useRef'
  resetBySwitchClient: boolean
  routes: string[]
  verdict: Verdict
  // Line the PR cites as evidence for this row's verdict, e.g. filing's comment inside
  // switchClient (App.tsx:698-701).
  citationLine?: number
  note: string
}

// `correctly-reset` covers TWO shapes, deliberately not split into a fifth verdict:
// (a) actively reset by switchClient (App.tsx:679-713), directly or via navigate('dashboard');
// (b) tenant-scoped or otherwise invariant across a company switch, so it cannot go stale.
// Rows 1, 2, 4, 5, 20, 22, 23, 24, 26, 28, 29 below are shape (b).

// Every route a screen reading an always-mounted atom can be on: the 13 ROUTE_PATHS
// entries (lib/route.ts:7-20). Sidebar and Header mount on all of them (App.tsx:1597,1599).
const ALL_13 = [
  '/',
  '/invoices',
  '/approvals',
  '/rules',
  '/customers',
  '/reports',
  '/workflows',
  '/clients',
  '/audit',
  '/settings',
  '/create',
  '/invoice',
  '/extraction',
]

export const AUDITED_ATOMS: readonly AuditedAtom[] = [
  {
    binding: 'suspended, setSuspended',
    name: 'suspended',
    line: 225,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ALL_13,
    verdict: 'correctly-reset',
    citationLine: 1590,
    note: 'Tenant/membership-scoped and latched, never unlatched -- it pre-empts the whole shell at App.tsx:1590. Every company here shares one tenant.',
  },
  {
    binding: 'clients, setClients',
    name: 'clients',
    line: 261,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ALL_13,
    verdict: 'correctly-reset',
    note: 'Tenant-scoped portfolio -- the switcher list itself. listEntities (lib/portfolio.ts:87-89) passes no entityId, and useAsync defaults deps to [], so the set is identical across a switch. Read by Sidebar and CreateUpload.',
  },
  {
    binding: 'activeEntityId, setActiveEntityId',
    name: 'activeEntityId',
    line: 268,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ALL_13,
    verdict: 'correctly-reset',
    citationLine: 680,
    note: 'The switch itself (App.tsx:680). No component reads it directly; every screen sees it through the `active` memo (App.tsx:281-282).',
  },
  {
    binding: '{ path: bootPath, search: bootSearch }',
    name: 'bootPath/bootSearch',
    line: 321,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: [],
    verdict: 'correctly-reset',
    note: 'Boot snapshot, never rewritten (no setter). Read only by the mount alignment effect, deps [].',
  },
  {
    binding: 'seed',
    name: 'seed',
    line: 333,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: [],
    verdict: 'correctly-reset',
    note: 'Boot parse of bootPath/bootSearch, no setter. Read only by the atom lazy initializers below it and the mount alignment effect.',
  },
  {
    binding: 'view, setView',
    name: 'view',
    line: 342,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ALL_13,
    verdict: 'correctly-reset',
    citationLine: 688,
    note: "navigate('dashboard') at App.tsx:688 sets it; carryView owns the resume rule (ROUTE-02).",
  },
  {
    binding: 'draft, setDraft',
    name: 'draft',
    line: 343,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citationLine: 691,
    note: 'Re-seeded from the incoming company at App.tsx:691. Read by CreateForm at createStep `form`.',
  },
  {
    binding: 'handOffDocumentId, setHandOffDocumentId',
    name: 'handOffDocumentId',
    line: 347,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: [],
    verdict: 'correctly-reset',
    citationLine: 692,
    note: 'Cleared at App.tsx:692. No screen reads it; only the fileDraft handler does.',
  },
  {
    binding: 'createStep, setCreateStep',
    name: 'createStep',
    line: 348,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create', '/imports/<ids>/review'],
    verdict: 'stale-and-reachable',
    citationLine: 611,
    note: "Reset to 'form' at App.tsx:693, but popstate re-arms it to 'review' at App.tsx:611 from an older entry. Fixed by ROUTE-06-02 (clamp) and pinned by ROUTE-06-04.",
  },
  {
    binding: 'reviewBatchIds, setReviewBatchIds',
    name: 'reviewBatchIds',
    line: 353,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create', '/imports/<ids>/review'],
    verdict: 'stale-and-reachable',
    citationLine: 610,
    note: 'Cleared at App.tsx:697, but popstate re-reads the ids out of an older review path at App.tsx:610. Fixed by ROUTE-06-02, pinned by ROUTE-06-04.',
  },
  {
    binding: 'groups, setGroups',
    name: 'groups',
    line: 360,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-but-unreachable',
    note: "Read by CreateMapping, which mounts only at createStep 'mapping'. switchClient sets 'form'; popstate can only reach 'review'. ROUTE-06-03 resets it anyway via resetImport.",
  },
  {
    binding: 'groupIndex, setGroupIndex',
    name: 'groupIndex',
    line: 361,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-but-unreachable',
    note: "Same CreateMapping gate as `groups`. ROUTE-06-03 resets it via resetImport.",
  },
  {
    binding: 'armedField, setArmedField',
    name: 'armedField',
    line: 362,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-but-unreachable',
    note: "Same CreateMapping gate. NOT in resetImport and NOT added by ROUTE-06-03 -- a column-arming cursor carries no company data.",
  },
  {
    binding: 'dragField, setDragField',
    name: 'dragField',
    line: 363,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-but-unreachable',
    note: 'Same CreateMapping gate. NOT in resetImport and NOT added by ROUTE-06-03 -- a transient drag cursor.',
  },
  {
    binding: 'detailInvoiceId, setDetailInvoiceId',
    name: 'detailInvoiceId',
    line: 366,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/invoice', '/invoices/<id>'],
    verdict: 'stale-and-reachable',
    citationLine: 595,
    note: 'Cleared at App.tsx:689, but popstate re-derives it from an older /invoices/<id> entry at App.tsx:595. Reaches the screen as ctx.importedInvoiceId, read by InvoiceDetail. Fixed by ROUTE-06-02.',
  },
  {
    binding: 'auditPrefilter, setAuditPrefilter',
    name: 'auditPrefilter',
    line: 371,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/audit', '/audit?invoice=<id>'],
    verdict: 'stale-and-reachable',
    citationLine: 604,
    note: "Cleared by navigate('dashboard') (App.tsx:642,648), but popstate re-arms it from ?invoice= at App.tsx:604-608. Found by this audit (D24); fixed by ROUTE-06-02's top-of-handler clamp, which drops the search string.",
  },
  {
    binding: 'extractionJobId, setExtractionJobId',
    name: 'extractionJobId',
    line: 376,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/extraction', '/extraction/<jobId>'],
    verdict: 'stale-and-reachable',
    citationLine: 596,
    note: 'Cleared at App.tsx:712 (ROUTE-01), but popstate re-derives it from an older /extraction/<jobId> entry at App.tsx:596. Reaches ExtractionReview as an explicit jobId prop (App.tsx:1625), which also gates the mount. Fixed by ROUTE-06-02.',
  },
  {
    binding: 'invoiceQuery, setInvoiceQuery_',
    name: 'invoiceQuery',
    line: 380,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: [...ALL_13, '/invoices?q=<text>'],
    verdict: 'deliberate',
    citationLine: 638,
    note: 'Durable by design (App.tsx:638-640). A filter text is not company data; the global search box keeps it across a switch.',
  },
  {
    binding: 'switcherOpen, setSwitcherOpen',
    name: 'switcherOpen',
    line: 381,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ALL_13,
    verdict: 'correctly-reset',
    citationLine: 690,
    note: 'Closed at App.tsx:690 -- the switcher that fired the switch. Read by Sidebar on every route.',
  },
  {
    binding: 'sandbox, setSandbox',
    name: 'sandbox',
    line: 384,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: [...ALL_13, '/settings/<tab>'],
    verdict: 'correctly-reset',
    note: 'A client-side constant (App.tsx:382-384), never fetched, so it carries no company dimension. Read by the always-mounted env banner and by SettingsView.',
  },
  {
    binding: 'settingsTab, setSettingsTab_',
    name: 'settingsTab',
    line: 387,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/settings', '/settings/<tab>'],
    verdict: 'deliberate',
    citationLine: 638,
    note: 'Durable by design (App.tsx:638-639); popstate re-clamps it by `mode` at App.tsx:600. A tab choice is not company data.',
  },
  {
    binding: 'connectors, setConnectors',
    name: 'connectors',
    line: 388,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/settings', '/settings/<tab>'],
    verdict: 'correctly-reset',
    note: 'Never fetched -- seeded from the INITIAL_CONNECTORS literal (App.tsx:122) and toggled locally, so it has no company dimension to go stale.',
  },
  {
    binding: 'connectorMappings, setConnectorMappings',
    name: 'connectorMappings',
    line: 391,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/settings', '/settings/<tab>'],
    verdict: 'correctly-reset',
    note: 'Never fetched; keyed by ConnectorId only (App.tsx:1331-1333), never by entity, so it has no company dimension to go stale.',
  },
  {
    binding: 'customRuleStore, setCustomRuleStore',
    name: 'customRuleStore',
    line: 397,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/rules'],
    verdict: 'correctly-reset',
    note: "Invariant by construction: reads and writes both go through customRulesKey(active.entityId), and only the resolved array reaches ctx. Caveat: every entity-less state collapses onto the shared 'workspace' bucket (lib/rules.ts:222-226).",
  },
  {
    binding: 'openRuleKey, setOpenRuleKey',
    name: 'openRuleKey',
    line: 398,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/rules'],
    verdict: 'correctly-reset',
    citationLine: 705,
    note: 'Cleared at App.tsx:705 -- rules are per company, so an open drawer would describe the company just left.',
  },
  {
    binding: 'policies, setPolicies',
    name: 'policies',
    line: 412,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/workflows', '/settings/<tab>'],
    verdict: 'correctly-reset',
    citationLine: 706,
    note: 'Tenant-scoped: listApprovalPolicies (lib/policies.ts:208) takes no params, so the set is unchanged by a switch (App.tsx:706-708 says so).',
  },
  {
    binding: 'editingPolicyId, setEditingPolicyId',
    name: 'editingPolicyId',
    line: 416,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/workflows'],
    verdict: 'correctly-reset',
    citationLine: 709,
    note: 'Cleared at App.tsx:709 so the next Workflows visit opens the list, not a half-edited builder.',
  },
  {
    binding: 'members, setMembers',
    name: 'members',
    line: 432,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/workflows', '/settings/<tab>', '/invoice', '/invoices/<id>'],
    verdict: 'correctly-reset',
    note: 'Tenant-scoped roster: listMembers (lib/members.ts:529) takes no params -- the same people before and after a switch.',
  },
  {
    binding: 'roles, setRoles',
    name: 'roles',
    line: 443,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/workflows', '/settings/<tab>'],
    verdict: 'correctly-reset',
    note: 'Tenant-scoped alongside `members`: listWorkflowRoles (lib/roles.ts:353) takes no params.',
  },
  {
    binding: 'entityId, setEntityId',
    name: 'entityId',
    line: 456,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-but-unreachable',
    note: "The import run's filing entity. Read by CreateMapping ('mapping' only). Reset by ROUTE-06-03; its AC-2 race assertion is still required.",
  },
  {
    binding: 'pickedFiles, setPickedFiles',
    name: 'pickedFiles',
    line: 460,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-and-reachable',
    note: "VERDICT CORRECTED by this audit: not gated behind a createStep. It reaches ctx as runKind (App.tsx:1517, runKindOf(pickedFiles)), and CreateFlow.tsx:37-38 feeds that to wizardHeader, whose strip renders unconditionally at CreateFlow.tsx:62-92 -- at every createStep, including the 'form' switchClient sets (App.tsx:693). Back onto /create therefore draws the previous company's wizard path. Fixed by ROUTE-06-03; coverage unchanged, resetImport already clears it.",
  },
  {
    binding: 'filesRefusal, setFilesRefusal',
    name: 'filesRefusal',
    line: 461,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-but-unreachable',
    note: "Read by CreateUpload, which mounts at 'upload' and 'documents' only. ROUTE-06-03 resets it via resetImport.",
  },
  {
    binding: 'run, setRun',
    name: 'run',
    line: 478,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create', '/imports/<ids>/review'],
    verdict: 'stale-and-reachable',
    note: "The only import atom genuinely reachable after a switch: CreateFlow's `importing = runIsActive(run)` gate is evaluated at EVERY createStep, including the 'form' switchClient sets. Fixed by ROUTE-06-03.",
  },
  {
    binding: 'documentStages, setDocumentStages',
    name: 'documentStages',
    line: 481,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create', '/imports/<ids>/review'],
    verdict: 'stale-but-unreachable',
    citationLine: 1085,
    note: "CAVEAT: unreachable only ONCE ROUTE-06-03 lands. On head it IS reachable through `run`, so its covering subtask is ROUTE-06-03 via `run`, not a reset of its own. Sole reader is ImportProgress via documentRunRows(run, stages) (lib/documentRun.ts:128-130), which maps run.files 1:1 and so returns [] for an empty list; ImportProgress.tsx:50 then returns null. Cleared at App.tsx:1085, not 477.",
  },
  {
    binding: 'importError, setImportError',
    name: 'importError',
    line: 482,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-but-unreachable',
    note: "Read by CreateUpload ('upload') and CreateMapping ('mapping') only (ctx.importError), neither reachable after a switch. ROUTE-06-03 resets it via resetImport.",
  },
  {
    binding: 'filing, setFiling',
    name: 'filing',
    line: 486,
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'deliberate',
    citationLine: 698,
    note: 'App.tsx:698-701: a request already in flight is still in flight and will land under the previous company. Leaving the button disabled until it settles is the honest frame. Do not clear.',
  },
  {
    binding: 'filingError, setFilingError',
    name: 'filingError',
    line: 487,
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citationLine: 702,
    note: 'Cleared at App.tsx:702 -- a distinct atom from `filing`; the failure message named the company just left.',
  },
  {
    binding: 'activeEntityIdRef',
    name: 'activeEntityIdRef',
    line: 287,
    kind: 'useRef',
    resetBySwitchClient: false,
    routes: [],
    verdict: 'correctly-reset',
    citationLine: 285,
    note: 'ROUTE-06-02. Not on ctx and no screen reads it: a latest-value mirror of active.entityId for the popstate handler, whose deps are [] and whose closure would otherwise freeze at mount. Written by the stamp backfill on every change of active.entityId, so it cannot go stale across a switch.',
  },
  {
    binding: 'reqInFlight',
    name: 'reqInFlight',
    line: 500,
    kind: 'useRef',
    resetBySwitchClient: false,
    routes: [],
    verdict: 'deliberate',
    citationLine: 698,
    note: 'Not on ctx and no screen reads it: a re-entrancy guard shared by four round trips (App.tsx:489-499) -- taken directly at :788, :932, :1034 and passed as `inFlight` into the filing call at :1240. Same in-flight rationale as `filing` (App.tsx:698-701).',
  },
]
