// Row shape for the Workspace atom-drift guard (App.atomAudit.test.tsx).
//
// ROUTE-06-02 QA. Rows carry NO line numbers. They did, and every one had to be remapped
// by hand each time App.tsx shifted -- a remap nothing verified, in a repo whose recorded
// failure mode is a citation that resolves to the wrong line. `binding` locates the
// declaration and `citation` locates the evidence, both by text, both proven to resolve to
// exactly one site by guard_everyCitationResolvesToExactlyOneSite.

export type Verdict = 'stale-and-reachable' | 'stale-but-unreachable' | 'correctly-reset' | 'deliberate'

// Evidence anchor: `path#Symbol` plus the statement, the convention that survives edits.
export type Citation = {
  // Marker for the enclosing symbol whose braced body scopes the search. Omit when `text`
  // is already unique across App.tsx.
  in?: string
  // A whole source line, trimmed. Must match EXACTLY ONE line in scope -- a needle that
  // matches two sites cites neither.
  text: string
}

export type AuditedAtom = {
  // Verbatim text extracted by the two regexes in App.atomAudit.test.tsx: an
  // `[x, setX]` pair for a useState atom, or the bare name for reqInFlight (useRef).
  binding: string
  name: string
  kind: 'useState' | 'useRef'
  resetBySwitchClient: boolean
  routes: string[]
  verdict: Verdict
  citation?: Citation
  note: string
}

// `correctly-reset` covers TWO shapes, deliberately not split into a fifth verdict:
// (a) actively reset by switchClient (App.tsx#switchClient), directly or via navigate('dashboard');
// (b) tenant-scoped or otherwise invariant across a company switch, so it cannot go stale.
// Shape (b): suspended, clients, bootPath/bootSearch, seed, sandbox, connectors,
// connectorMappings, customRuleStore, policies, members, roles. Named, not indexed --
// inserting a row renumbers an index list and nothing catches it.

// Every route a screen reading an always-mounted atom can be on: the 13 ROUTE_PATHS
// entries (lib/route.ts:7-20). Sidebar and Header mount on all of them (App.tsx#Workspace).
export const ALL_13 = [
  '/',
  '/invoices',
  '/approvals',
  '/rules',
  '/customers',
  '/reports',
  '/workflows',
  '/clients',
  '/audit',
  '/settings',
  '/create',
  '/invoice',
  '/extraction',
]

export const AUDITED_ATOMS: readonly AuditedAtom[] = [
  {
    binding: 'suspended, setSuspended',
    name: 'suspended',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ALL_13,
    verdict: 'correctly-reset',
    citation: { text: 'if (suspended) return <SuspendedNotice onSignOut={onSignOut} />' },
    note: 'Tenant/membership-scoped and latched, never unlatched -- it pre-empts the whole shell at App.tsx#Workspace. Every company here shares one tenant.',
  },
  {
    binding: 'clients, setClients',
    name: 'clients',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ALL_13,
    verdict: 'correctly-reset',
    note: 'Tenant-scoped portfolio -- the switcher list itself. listEntities (lib/portfolio.ts:87-89) passes no entityId, and useAsync defaults deps to [], so the set is identical across a switch. Read by Sidebar and CreateUpload.',
  },
  {
    binding: 'activeEntityId, setActiveEntityId',
    name: 'activeEntityId',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ALL_13,
    verdict: 'correctly-reset',
    citation: { text: 'setActiveEntityId(id)' },
    note: 'The switch itself (App.tsx#switchClient). No component reads it directly; every screen sees it through the `active` memo (App.tsx#Workspace).',
  },
  {
    binding: '{ path: bootPath, search: bootSearch }',
    name: 'bootPath/bootSearch',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: [],
    verdict: 'correctly-reset',
    note: 'Boot snapshot, never rewritten (no setter). Read only by the mount alignment effect, deps [].',
  },
  {
    binding: 'seed',
    name: 'seed',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: [],
    verdict: 'correctly-reset',
    note: 'Boot parse of bootPath/bootSearch, no setter. Read only by the atom lazy initializers below it and the mount alignment effect.',
  },
  {
    binding: 'view, setView',
    name: 'view',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ALL_13,
    verdict: 'correctly-reset',
    citation: { text: 'navigate(\'dashboard\')' },
    note: "navigate('dashboard') at App.tsx#switchClient sets it; carryView owns the resume rule (ROUTE-02).",
  },
  {
    binding: 'draft, setDraft',
    name: 'draft',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citation: { text: 'setDraft(defaultDraft(clients.find((c) => c.entityId === id) ?? active))' },
    note: 'Re-seeded from the incoming company at App.tsx#switchClient. Read by CreateForm at createStep `form`.',
  },
  {
    binding: 'handOffDocumentId, setHandOffDocumentId',
    name: 'handOffDocumentId',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: [],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'setHandOffDocumentId(null)' },
    note: 'Cleared at App.tsx#switchClient. No screen reads it; only the fileDraft handler does.',
  },
  {
    binding: 'createStep, setCreateStep',
    name: 'createStep',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create', '/imports/<ids>/review'],
    verdict: 'stale-and-reachable',
    citation: { in: 'const onPopState = (event: PopStateEvent) =>', text: 'setCreateStep(\'review\')' },
    note: "Reset to 'form' at App.tsx#switchClient, but popstate re-arms it to 'review' at App.tsx#onPopState from an older entry. Cross-company case unreachable since ROUTE-06-02 (clamp collapses view off 'create'); same-company bare-/create case fixed by ROUTE-06-04's else-if arm.",
  },
  {
    binding: 'reviewBatchIds, setReviewBatchIds',
    name: 'reviewBatchIds',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create', '/imports/<ids>/review'],
    verdict: 'stale-and-reachable',
    citation: { text: 'setReviewBatchIds(at.reviewBatchIds)' },
    note: "Cleared at App.tsx#switchClient, but popstate re-reads the ids out of an older review path at App.tsx#onPopState. Cross-company case unreachable since ROUTE-06-02 (clamp collapses view off 'create'); same-company bare-/create case fixed by ROUTE-06-04's else-if arm.",
  },
  {
    binding: 'groups, setGroups',
    name: 'groups',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'resetImport(id)' },
    note: "Read by CreateMapping, which mounts only at createStep 'mapping' -- unreachable post-switch regardless. Cleared by App.tsx#switchClient's resetImport(id) call (ROUTE-06-03).",
  },
  {
    binding: 'groupIndex, setGroupIndex',
    name: 'groupIndex',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'resetImport(id)' },
    note: "Same CreateMapping gate as `groups`. Cleared by App.tsx#switchClient's resetImport(id) call (ROUTE-06-03).",
  },
  {
    binding: 'armedField, setArmedField',
    name: 'armedField',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-but-unreachable',
    note: "Same CreateMapping gate. NOT in resetImport and NOT added by ROUTE-06-03 -- a column-arming cursor carries no company data.",
  },
  {
    binding: 'dragField, setDragField',
    name: 'dragField',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'stale-but-unreachable',
    note: 'Same CreateMapping gate. NOT in resetImport and NOT added by ROUTE-06-03 -- a transient drag cursor.',
  },
  {
    binding: 'detailInvoiceId, setDetailInvoiceId',
    name: 'detailInvoiceId',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/invoice', '/invoices/<id>'],
    verdict: 'stale-and-reachable',
    citation: { text: 'setDetailInvoiceId(at.invoiceId)' },
    note: 'Cleared at App.tsx#switchClient, but popstate re-derives it from an older /invoices/<id> entry at App.tsx#onPopState. Reaches the screen as ctx.importedInvoiceId, read by InvoiceDetail. Fixed by ROUTE-06-02.',
  },
  {
    binding: 'auditPrefilter, setAuditPrefilter',
    name: 'auditPrefilter',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/audit', '/audit?invoice=<id>'],
    verdict: 'stale-and-reachable',
    citation: { in: 'const onPopState = (event: PopStateEvent) =>', text: 'setAuditPrefilter((prev) =>' },
    note: "Cleared by navigate('dashboard') (App.tsx#navigate), but popstate re-arms it from ?invoice= at App.tsx#onPopState. Found by this audit (D24); fixed by ROUTE-06-02's top-of-handler clamp, which drops the search string.",
  },
  {
    binding: 'extractionJobId, setExtractionJobId',
    name: 'extractionJobId',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/extraction', '/extraction/<jobId>'],
    verdict: 'stale-and-reachable',
    citation: { text: 'setExtractionJobId(at.jobId)' },
    note: 'Cleared at App.tsx#switchClient (ROUTE-01), but popstate re-derives it from an older /extraction/<jobId> entry at App.tsx#onPopState. Reaches ExtractionReview as an explicit jobId prop (App.tsx#Workspace), which also gates the mount. Fixed by ROUTE-06-02.',
  },
  {
    binding: 'invoiceQuery, setInvoiceQuery_',
    name: 'invoiceQuery',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: [...ALL_13, '/invoices?q=<text>'],
    verdict: 'deliberate',
    citation: { text: '// settingsTab and q are DURABLE -- a param overrides, absence leaves state alone.' },
    note: 'Durable by design (App.tsx#navigate). A filter text is not company data; the global search box keeps it across a switch.',
  },
  {
    binding: 'switcherOpen, setSwitcherOpen',
    name: 'switcherOpen',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ALL_13,
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'setSwitcherOpen(false)' },
    note: 'Closed at App.tsx#switchClient -- the switcher that fired the switch. Read by Sidebar on every route.',
  },
  {
    binding: 'sandbox, setSandbox',
    name: 'sandbox',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: [...ALL_13, '/settings/<tab>'],
    verdict: 'correctly-reset',
    note: 'A client-side constant (App.tsx#Workspace), never fetched, so it carries no company dimension. Read by the always-mounted env banner and by SettingsView.',
  },
  {
    binding: 'settingsTab, setSettingsTab_',
    name: 'settingsTab',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/settings', '/settings/<tab>'],
    verdict: 'deliberate',
    citation: { text: '// settingsTab and q are DURABLE -- a param overrides, absence leaves state alone.' },
    note: 'Durable by design (App.tsx#navigate); popstate re-clamps it by `mode` at App.tsx#onPopState. A tab choice is not company data.',
  },
  {
    binding: 'connectors, setConnectors',
    name: 'connectors',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/settings', '/settings/<tab>'],
    verdict: 'correctly-reset',
    note: 'Never fetched -- seeded from the INITIAL_CONNECTORS literal (App.tsx#INITIAL_CONNECTORS) and toggled locally, so it has no company dimension to go stale.',
  },
  {
    binding: 'connectorMappings, setConnectorMappings',
    name: 'connectorMappings',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/settings', '/settings/<tab>'],
    verdict: 'correctly-reset',
    note: 'Never fetched; keyed by ConnectorId only (App.tsx#saveConnectorMapping), never by entity, so it has no company dimension to go stale.',
  },
  {
    binding: 'customRuleStore, setCustomRuleStore',
    name: 'customRuleStore',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/rules'],
    verdict: 'correctly-reset',
    note: "Invariant by construction: reads and writes both go through customRulesKey(active.entityId), and only the resolved array reaches ctx. Caveat: every entity-less state collapses onto the shared 'workspace' bucket (lib/rules.ts:222-226).",
  },
  {
    binding: 'openRuleKey, setOpenRuleKey',
    name: 'openRuleKey',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/rules'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'setOpenRuleKey(null)' },
    note: 'Cleared at App.tsx#switchClient -- rules are per company, so an open drawer would describe the company just left.',
  },
  {
    binding: 'policies, setPolicies',
    name: 'policies',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/workflows', '/settings/<tab>'],
    verdict: 'correctly-reset',
    citation: { text: '// Policies are per tenant, so the SET is unchanged — but the switch lands on the' },
    note: 'Tenant-scoped: listApprovalPolicies (lib/policies.ts:208) takes no params, so the set is unchanged by a switch (App.tsx#switchClient says so).',
  },
  {
    binding: 'editingPolicyId, setEditingPolicyId',
    name: 'editingPolicyId',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/workflows'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'setEditingPolicyId(null)' },
    note: 'Cleared at App.tsx#switchClient so the next Workflows visit opens the list, not a half-edited builder.',
  },
  {
    binding: 'members, setMembers',
    name: 'members',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/workflows', '/settings/<tab>', '/invoice', '/invoices/<id>'],
    verdict: 'correctly-reset',
    note: 'Tenant-scoped roster: listMembers (lib/members.ts:529) takes no params -- the same people before and after a switch.',
  },
  {
    binding: 'roles, setRoles',
    name: 'roles',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/workflows', '/settings/<tab>'],
    verdict: 'correctly-reset',
    note: 'Tenant-scoped alongside `members`: listWorkflowRoles (lib/roles.ts:353) takes no params.',
  },
  {
    binding: 'entityId, setEntityId',
    name: 'entityId',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'resetImport(id)' },
    note: "The import run's filing entity. Read by CreateMapping ('mapping' only). Cleared and re-seeded from the INCOMING id by App.tsx#switchClient's resetImport(id) call (ROUTE-06-03); its AC-2 race assertion pins that the value is B, never A or null.",
  },
  {
    binding: 'pickedFiles, setPickedFiles',
    name: 'pickedFiles',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'resetImport(id)' },
    note: "Reachable via `run`, not a createStep gate: not via wizardHeader, whose module-private single-step allowlist (lib/importFlow.ts) short-circuits at the 'form' step switchClient sets, before runKind is ever read. Reaches ctx as runKind (App.tsx#Workspace, runKindOf(pickedFiles)); sole reader at 'form' is ImportProgress (components/ImportProgress.tsx#ImportProgress), gated by the same `importing = runIsActive(run)` as `run` itself. Cleared by App.tsx#switchClient's resetImport(id) call (ROUTE-06-03).",
  },
  {
    binding: 'filesRefusal, setFilesRefusal',
    name: 'filesRefusal',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'resetImport(id)' },
    note: "Read by CreateUpload, which mounts at 'upload' and 'documents' only -- unreachable post-switch regardless of the reset. Cleared by App.tsx#switchClient's resetImport(id) call (ROUTE-06-03).",
  },
  {
    binding: 'run, setRun',
    name: 'run',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create', '/imports/<ids>/review'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'resetImport(id)' },
    note: "The only import atom directly reachable after a switch: CreateFlow's `importing = runIsActive(run)` gate is evaluated at EVERY createStep, including the 'form' switchClient sets. Cleared by App.tsx#switchClient's resetImport(id) call (ROUTE-06-03).",
  },
  {
    binding: 'documentStages, setDocumentStages',
    name: 'documentStages',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create', '/imports/<ids>/review'],
    verdict: 'stale-but-unreachable',
    citation: { text: 'setDocumentStages({})' },
    note: "Unreachable because ROUTE-06-03's resetImport(id) clears `run`, not because this atom is reset itself -- its own declaration is never touched by switchClient. Sole reader is ImportProgress via documentRunRows(run, stages) (lib/documentRun.ts:128-130), which maps run.files 1:1 and so returns [] once `run` is empty. Cleared at App.tsx#startDocumentRun, never at its declaration.",
  },
  {
    binding: 'importError, setImportError',
    name: 'importError',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'resetImport(id)' },
    note: "Read by CreateUpload ('upload') and CreateMapping ('mapping') only (ctx.importError), neither reachable after a switch regardless. Cleared by App.tsx#switchClient's resetImport(id) call (ROUTE-06-03).",
  },
  {
    binding: 'filing, setFiling',
    name: 'filing',
    kind: 'useState',
    resetBySwitchClient: false,
    routes: ['/create'],
    verdict: 'deliberate',
    citation: { text: '// A failed filing\'s message named the company just left. `filing` is deliberately NOT' },
    note: 'App.tsx#switchClient: a request already in flight is still in flight and will land under the previous company. Leaving the button disabled until it settles is the honest frame. Do not clear.',
  },
  {
    binding: 'filingError, setFilingError',
    name: 'filingError',
    kind: 'useState',
    resetBySwitchClient: true,
    routes: ['/create'],
    verdict: 'correctly-reset',
    citation: { in: 'function switchClient(id: string)', text: 'setFilingError(null)' },
    note: 'Cleared at App.tsx#switchClient -- a distinct atom from `filing`; the failure message named the company just left.',
  },
  {
    binding: 'activeEntityIdRef',
    name: 'activeEntityIdRef',
    kind: 'useRef',
    resetBySwitchClient: false,
    routes: [],
    verdict: 'correctly-reset',
    citation: { text: '// Latest-value mirror of active.entityId for the popstate handler, whose deps are [] --' },
    note: 'ROUTE-06-02. Not on ctx and no screen reads it: a latest-value mirror of active.entityId for the popstate handler, whose deps are [] and whose closure would otherwise freeze at mount. Written by the stamp backfill on every change of active.entityId, so it cannot go stale across a switch.',
  },
  {
    binding: 'reqInFlight',
    name: 'reqInFlight',
    kind: 'useRef',
    resetBySwitchClient: false,
    routes: [],
    verdict: 'deliberate',
    citation: { text: '// A failed filing\'s message named the company just left. `filing` is deliberately NOT' },
    note: 'Not on ctx and no screen reads it: a re-entrancy guard taken directly by App.tsx#readAllColumns, App.tsx#startRun and App.tsx#startDocumentRun, and passed as `inFlight` into the filing call in App.tsx#fileDraft. Same in-flight rationale as `filing` (App.tsx#switchClient).',
  },
]
