// wild_adversarial_test.go: QA's hardening of the four wild_ arrangements -- the pin every
// other wild loop borrows its non-emptiness from, the two defects these fixtures do NOT
// reproduce, and the golden properties nothing else reads. No database.
package endtoend

import (
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/SimonOsipov/invoice-os/internal/extraction"
)

// wildLayoutCount pins the arrangement count. Every wild spec loops over wildLayouts without a
// non-emptiness guard of its own; this is where an emptied slice fails.
const wildLayoutCount = 4

// TestWildLayouts_TheLayoutSetIsPinnedAndCarriedByEveryTable holds the one collection the whole
// file iterates, and every table that must name each member.
func TestWildLayouts_TheLayoutSetIsPinnedAndCarriedByEveryTable(t *testing.T) {
	if len(wildLayouts) != wildLayoutCount {
		t.Fatalf("wildLayouts names %d layout(s) %v, want %d -- every loop over it would assert that much less", len(wildLayouts), wildLayouts, wildLayoutCount)
	}
	seen := map[string]bool{}
	for _, layout := range wildLayouts {
		if seen[layout] {
			t.Errorf("wildLayouts names %s twice; a duplicate inflates every count taken over it", layout)
		}
		seen[layout] = true
		if !strings.HasPrefix(layout, "wild_") || !strings.HasSuffix(layout, ".pdf") {
			t.Errorf("wildLayouts names %q, which is not a wild_*.pdf arrangement", layout)
		}
	}

	fixtures := wildReadFile(t, wildFixturesFile)
	for _, layout := range wildLayouts {
		golden := wildGolden(layout)
		if !slices.Contains(requiredPDFs, layout) {
			t.Errorf("requiredPDFs does not name %s", layout)
		}
		if !slices.Contains(requiredGoldens, golden) {
			t.Errorf("requiredGoldens does not name %s", golden)
		}
		if _, ok := wildTokenFloor[layout]; !ok {
			t.Errorf("wildTokenFloor does not name %s", layout)
		}
		if _, ok := eeLinesExpected[layout]; !ok {
			t.Errorf("eeLinesExpected does not name %s; its reached figure would score against no denominator at all", layout)
		}
		if !slices.ContainsFunc(expectByLayout, func(r struct {
			file   string
			fields map[string][]string
		}) bool {
			return r.file == layout
		}) {
			t.Errorf("expectByLayout does not name %s", layout)
		}
		if !strings.Contains(fixtures, layout) {
			t.Errorf("%s does not name %s; the arrangement is scored here and generated by nothing", wildFixturesFile, layout)
		}
	}
}

// --- the defects these arrangements do NOT reproduce ----------------------------------------

// wildResolved is every Tier-1 candidate value one layout produces for field, in rank order.
// Resolve makes no decision, so this is the set a later tie-break would have to choose from.
func wildResolved(t *testing.T, layout, field string) []string {
	t.Helper()
	var out []string
	for _, c := range extraction.Resolve(eeTokenPages(t, layout), extraction.RuleSet{Tier1: extraction.Tier1Rules}) {
		if c.Field == field {
			out = append(out, c.Value)
		}
	}
	if len(out) == 0 {
		t.Fatalf("%s produced no %s candidate at all; the assertions below would hold over nothing", layout, field)
	}
	return out
}

// TestWildLayouts_TheRuledTableDoesNotReproduceACompetingTotal records a measured non-result.
// The story lists "a line-item figure chosen as the total" as this layout's Objective defect and
// AC-13 assumes the totals must be picked OVER the last line amount. Measured: no total rule
// reaches that amount, so total has exactly one candidate and there is no pick to make. EXTR-23
// must supply its own oracle, or make this arrangement truer -- putting the competing amount on
// the totals label's own baseline, which is what a `right` relation can see.
//
// Fails the moment the fixture starts reproducing the defect, which is the point: the day this
// reds is the day EXTR-23 gets its oracle back.
func TestWildLayouts_TheRuledTableDoesNotReproduceACompetingTotal(t *testing.T) {
	got := wildResolved(t, wildRuled, "total")
	want := wildOneValue(t, wildRuled, "total")

	if !slices.Equal(got, []string{want}) {
		t.Errorf("%s now resolves total to %v, not the single uncontested %q this arrangement was measured at; re-read whether the competing line amount finally competes", wildRuled, got, want)
	}
	if slices.Contains(got, wildRuledLastLineAmount) {
		t.Errorf("%s now reaches the last line amount %s as a total candidate; the defect IS reproduced and eeRealMisses must gain the cell", wildRuled, wildRuledLastLineAmount)
	}
}

// TestWildLayouts_TheRCLayoutDoesNotReproduceItsDateOrVATDefect records the other two measured
// non-results. The story lists three Objective defects for this arrangement; only the naira
// yielding no currency is reproduced.
//
//   - Due Date above Issue Date: BOTH dates reach issue_date, but the printed issue date wins on
//     distance because "Issue Date " is the longer label. The confusion is reachable and never
//     decided, so the fixture is one dial from being an oracle.
//   - RC number beside the VAT line: vat has one candidate. The RC line displaces nothing.
func TestWildLayouts_TheRCLayoutDoesNotReproduceItsDateOrVATDefect(t *testing.T) {
	dates := wildResolved(t, wildRCNaira, "issue_date")
	issue := wildOneValue(t, wildRCNaira, "issue_date")
	const wildRCDueDate = "2026-08-07"

	if !slices.Contains(dates, wildRCDueDate) {
		t.Errorf("%s no longer reaches the due date %s as an issue_date candidate; the arrangement stopped even being able to confuse the two", wildRCNaira, wildRCDueDate)
	}
	if len(dates) == 0 || dates[0] != issue {
		t.Errorf("%s ranks issue_date %v; the printed issue date %q was measured at rank 0, so the Due Date defect is NOT reproduced and EXTR-22 must supply its own oracle", wildRCNaira, dates, issue)
	}

	vat := wildResolved(t, wildRCNaira, "vat")
	if !slices.Equal(vat, []string{wildOneValue(t, wildRCNaira, "vat")}) {
		t.Errorf("%s now resolves vat to %v; the RC line displaced nothing when this was measured, and eeRealMisses must gain the cell if it does now", wildRCNaira, vat)
	}
}

// TestWildLayouts_TheTwoPartyDefectsAreReproduced is the positive control for the two above: the
// same candidate read, on the arrangement that DOES reproduce its Objective defects. Without it
// a Resolve that stopped producing candidates at all would read as two clean non-results.
func TestWildLayouts_TheTwoPartyDefectsAreReproduced(t *testing.T) {
	if got := wildResolved(t, wildTwoParty, "supplier_tin"); !slices.Contains(got, wildTINs[1]) {
		t.Errorf("%s no longer binds the buyer TIN %s to supplier_tin (%v); EXTR-22's oracle is gone", wildTwoParty, wildTINs[1], got)
	}
	names := wildResolved(t, wildTwoParty, "buyer_name")
	if len(names) == 0 || names[0] == "Honeywell Group" {
		t.Errorf("%s ranks buyer_name %v with the real name first; the label fragment no longer wins and EXTR-22's oracle is gone", wildTwoParty, names)
	}
	if !slices.ContainsFunc(names, func(s string) bool { return strings.Contains(s, "No.") || strings.Contains(s, "Signature") }) {
		t.Errorf("%s reaches no label fragment for buyer_name (%v)", wildTwoParty, names)
	}
}

// --- golden properties nothing else reads -----------------------------------------------------

// TestWildGoldens_TheRuledTableCellsAgreeWithItsOwnTokens closes the seam between the two golden
// specs: AC-2 compares tokens against pdfium and AC-10b reads only the header row, so a
// hand-edited body cell is caught by the container step in CI and by nothing in Go.
func TestWildGoldens_TheRuledTableCellsAgreeWithItsOwnTokens(t *testing.T) {
	pages := eeGoldenPages(t, wildGolden(wildRuled))

	var tokens []string
	cells := 0
	for _, p := range pages {
		for _, tok := range p.Tokens {
			tokens = append(tokens, strings.TrimSpace(tok.Text))
		}
	}
	for _, p := range pages {
		for _, tbl := range p.Tables {
			for _, cell := range tbl.Cells {
				text := strings.TrimSpace(cell.Text)
				if text == "" {
					continue
				}
				cells++
				if !slices.Contains(tokens, text) {
					t.Errorf("%s's table carries cell %q, which its own token list does not; the golden was hand-edited", wildGolden(wildRuled), text)
				}
			}
		}
	}
	if cells == 0 || len(tokens) == 0 {
		t.Fatalf("%s yielded %d table cell(s) and %d token(s); the comparison above held over nothing", wildGolden(wildRuled), cells, len(tokens))
	}
}

// TestWildGoldens_CarryRawUTF8AndNeverAnEscape is the property `ensure_ascii=False` exists for.
// Go's json.MarshalIndent writes raw UTF-8, so an escaped ₦ could never round-trip through
// TestWildGoldens_AreMachineGenerated -- but only after somebody regenerates. This reds on the
// committed bytes.
func TestWildGoldens_CarryRawUTF8AndNeverAnEscape(t *testing.T) {
	entries, err := os.ReadDir(eeFxDir)
	if err != nil {
		t.Fatalf("read %s: %v", eeFxDir, err)
	}
	nonASCII, scanned := 0, 0
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".docling.json") {
			continue
		}
		scanned++
		raw := eeFixtureBytes(t, e.Name())
		if strings.Contains(string(raw), `\u`) {
			t.Errorf("%s carries a \\u escape; the golden writer lost ensure_ascii=False and Go can never re-serialise it byte-for-byte", e.Name())
		}
		for _, b := range raw {
			if b > 0x7f {
				nonASCII++
				break
			}
		}
	}
	if scanned == 0 {
		t.Fatalf("%s holds no golden; the scan above asserts an absence and found nothing", eeFxDir)
	}
	// Floor: an all-ASCII corpus passes the escape clause for the wrong reason.
	if nonASCII == 0 {
		t.Errorf("no committed golden carries a non-ASCII byte; the naira arrangements are gone and this scan proves nothing about ensure_ascii=False")
	}
}
