// wild_adversarial_test.go: QA's hardening of the four wild_ arrangements -- the pin every
// other wild loop borrows its non-emptiness from, the two defects these fixtures do NOT
// reproduce, and the golden properties nothing else reads. No database.
package endtoend

import (
	"cmp"
	"os"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/SimonOsipov/invoice-os/internal/extraction"
)

// wildLayoutCount pins the arrangement count. Every wild spec loops over wildLayouts without a
// non-emptiness guard of its own; this is where an emptied slice fails.
const wildLayoutCount = 5

// TestWildLayouts_TheLayoutSetIsPinnedAndCarriedByEveryTable holds the one collection the whole
// file iterates, and every table that must name each member.
func TestWildLayouts_TheLayoutSetIsPinnedAndCarriedByEveryTable(t *testing.T) {
	if len(wildLayouts) != wildLayoutCount {
		t.Fatalf("wildLayouts names %d layout(s) %v, want %d -- every loop over it would assert that much less", len(wildLayouts), wildLayouts, wildLayoutCount)
	}
	seen := map[string]bool{}
	for _, layout := range wildLayouts {
		if seen[layout] {
			t.Errorf("wildLayouts names %s twice; a duplicate inflates every count taken over it", layout)
		}
		seen[layout] = true
		if !strings.HasPrefix(layout, "wild_") || !strings.HasSuffix(layout, ".pdf") {
			t.Errorf("wildLayouts names %q, which is not a wild_*.pdf arrangement", layout)
		}
	}

	fixtures := wildReadFile(t, wildFixturesFile)
	for _, layout := range wildLayouts {
		golden := wildGolden(layout)
		if !slices.Contains(requiredPDFs, layout) {
			t.Errorf("requiredPDFs does not name %s", layout)
		}
		if !slices.Contains(requiredGoldens, golden) {
			t.Errorf("requiredGoldens does not name %s", golden)
		}
		if _, ok := wildTokenFloor[layout]; !ok {
			t.Errorf("wildTokenFloor does not name %s", layout)
		}
		if _, ok := eeLinesExpected[layout]; !ok {
			t.Errorf("eeLinesExpected does not name %s; its reached figure would score against no denominator at all", layout)
		}
		if !slices.ContainsFunc(expectByLayout, func(r struct {
			file   string
			fields map[string][]string
		}) bool {
			return r.file == layout
		}) {
			t.Errorf("expectByLayout does not name %s", layout)
		}
		if !strings.Contains(fixtures, layout) {
			t.Errorf("%s does not name %s; the arrangement is scored here and generated by nothing", wildFixturesFile, layout)
		}
	}
}

// wildScannedTwins names the five golden-sourced twins the image-only layout needs, one per
// pdfium-sourced spec that moved to wildTextLayouts. This pins that they EXIST; it cannot pin
// that they assert anything -- each twin carries its own anti-vacuity floor for that.
var wildScannedTwins = []string{
	"TestWildGoldens_TheScannedGoldenDescribesAnImageOnlyPDF",
	"TestWildLayouts_TheScannedLayoutUsesOnlyFreeReservedTINs",
	"TestWildLayouts_TheScannedLayoutsExpectedValuesAppearInItsGolden",
	"TestWildGoldens_TheScannedLayoutHasAGoldenTokenFloor",
	"TestWildLayouts_TheScannedLayoutUsesOnlySynthesizedIdentifiers",
}

const wildGoldensFile = "goldens_test.go"

// TestWildLayouts_TheLayoutSetPartitionsIntoTextAndScanned holds the split exhaustive rather
// than conventional: a sixth layout appended to wildLayouts alone cannot slip past all five
// moved specs unnoticed. The property clause is what makes this more than a naming rule.
func TestWildLayouts_TheLayoutSetPartitionsIntoTextAndScanned(t *testing.T) {
	if !slices.Equal(wildLayouts, append(slices.Clone(wildTextLayouts), wildScanned)) {
		t.Fatalf("wildLayouts is %v, want wildTextLayouts %v followed by %s -- the two halves no longer exhaust it", wildLayouts, wildTextLayouts, wildScanned)
	}
	if slices.Contains(wildTextLayouts, wildScanned) {
		t.Errorf("wildTextLayouts names %s; the two halves must be disjoint", wildScanned)
	}

	for _, layout := range wildTextLayouts {
		if got := wildTokenCount(wildPDFiumPages(t, layout)); got == 0 {
			t.Errorf("%s is in wildTextLayouts and reads 0 pdfium token(s); every spec that loops that slice would fatal on it", layout)
		}
	}
	if got := wildTokenCount(wildPDFiumPages(t, wildScanned)); got != 0 {
		t.Errorf("%s reads %d pdfium token(s), want exactly 0 -- a layout with a text layer does not belong in the scanned slot", wildScanned, got)
	}

	src := wildReadFile(t, wildGoldensFile)
	for _, name := range wildScannedTwins {
		if !strings.Contains(src, name) {
			t.Errorf("%s declares no %s; the pdfium-sourced spec it replaces now covers four layouts and nothing covers the fifth", wildGoldensFile, name)
		}
	}
}

// --- what these arrangements do and do not reproduce -----------------------------------------

// wildResolved is every Tier-1 candidate value one layout produces for field, in rank order.
// Resolve makes no decision, so this is the set a later tie-break would have to choose from.
func wildResolved(t *testing.T, layout, field string) []string {
	t.Helper()
	var out []string
	for _, c := range extraction.Resolve(eeTokenPages(t, layout), extraction.RuleSet{Tier1: extraction.Tier1Rules}) {
		if c.Field == field {
			out = append(out, c.Value)
		}
	}
	if len(out) == 0 {
		t.Fatalf("%s produced no %s candidate at all; the assertions below would hold over nothing", layout, field)
	}
	return out
}

// TestWildLayouts_TheRuledTableReproducesACompetingTotal is EXTR-23's oracle. The Total label
// continues on the last data row's baseline, so t1.total.right reaches that row's amount and the
// printed 8,600.00 falls outside every total relation: total resolves to the LINE figure, which
// is the Objective defect "a line-item figure chosen as the total".
//
// The candidate list, not the page: an amount readable somewhere on the page is not an amount a
// rule can pick, which is the reading that let this arrangement score 8/8 while reproducing
// nothing.
func TestWildLayouts_TheRuledTableReproducesACompetingTotal(t *testing.T) {
	got := wildResolved(t, wildRuled, "total")
	printed := wildOneValue(t, wildRuled, "total")

	if !slices.Equal(got, []string{wildRuledLastLineAmount}) {
		t.Errorf("%s resolves total to %v, want exactly [%s] -- the last line amount must be the only candidate, or EXTR-23 has no defect to fix", wildRuled, got, wildRuledLastLineAmount)
	}
	if slices.Contains(got, printed) {
		t.Errorf("%s reaches the printed total %s as a candidate (%v); the defect is no longer reproduced and EXTR-23 loses its oracle", wildRuled, printed, got)
	}
}

// TestWildLayouts_TheRCLayoutDoesNotReproduceItsDateOrVATDefect records two measured
// NON-reproductions: this corpus gives EXTR-22's Due-Date half and the RC-as-VAT half NO ORACLE,
// and the owning story must supply its own. The story lists three Objective defects for this
// arrangement; only the naira yielding no currency is reproduced.
//
//   - Due Date above Issue Date: BOTH dates reach issue_date, but the printed issue date wins on
//     distance because "Issue Date " is the longer label. The confusion is reachable and never
//     decided, so the fixture is one dial from being an oracle.
//   - RC number beside the VAT line: vat has one candidate. The RC line displaces nothing.
//
// Fails the moment either starts reproducing, which is the point: the day this reds is the day
// EXTR-22 gets an oracle here.
func TestWildLayouts_TheRCLayoutDoesNotReproduceItsDateOrVATDefect(t *testing.T) {
	dates := wildResolved(t, wildRCNaira, "issue_date")
	issue := wildOneValue(t, wildRCNaira, "issue_date")
	const wildRCDueDate = "2026-08-07"

	if !slices.Contains(dates, wildRCDueDate) {
		t.Errorf("%s no longer reaches the due date %s as an issue_date candidate; the arrangement stopped even being able to confuse the two", wildRCNaira, wildRCDueDate)
	}
	if len(dates) == 0 || dates[0] != issue {
		t.Errorf("%s ranks issue_date %v; the printed issue date %q was measured at rank 0. NO ORACLE HERE for EXTR-22's Due-Date half -- this corpus does not reproduce it and EXTR-22 must supply its own", wildRCNaira, dates, issue)
	}

	vat := wildResolved(t, wildRCNaira, "vat")
	if !slices.Equal(vat, []string{wildOneValue(t, wildRCNaira, "vat")}) {
		t.Errorf("%s now resolves vat to %v; the RC line displaced nothing when this was measured. NO ORACLE HERE for the RC-as-VAT half -- if it displaces something now, eeRealMisses must gain the cell", wildRCNaira, vat)
	}
}

// The two specs above assert absences, so their positive control is now
// TestWildLayouts_TheTwoPartyBuyerNameIsTheName, which reads the name at rank 0, and
// TestWildLayouts_TheTwoPartyTINsBindToTheirOwnParty, which reads each party's TIN at any rank,
// both on wild_two_party_bare_tin.pdf.

// --- golden properties nothing else reads -----------------------------------------------------

// wildCellTokens rebuilds one cell's text from the golden's own tokens: those whose centre sits
// inside the cell's box, joined left to right. It also returns how many tokens that took. A cell
// carrying no box rebuilds to "".
func wildCellTokens(p extraction.Page, cell extraction.TableCell) (string, int) {
	if cell.Region == nil {
		return "", 0
	}
	var inside []extraction.Token
	for _, tok := range p.Tokens {
		cx, cy := (tok.Region.X0+tok.Region.X1)/2, (tok.Region.Y0+tok.Region.Y1)/2
		if cx >= cell.Region.X0 && cx <= cell.Region.X1 && cy >= cell.Region.Y0 && cy <= cell.Region.Y1 {
			inside = append(inside, tok)
		}
	}
	slices.SortFunc(inside, func(a, b extraction.Token) int { return cmp.Compare(a.Region.X0, b.Region.X0) })

	var parts []string
	for _, tok := range inside {
		parts = append(parts, strings.TrimSpace(tok.Text))
	}
	return strings.Join(parts, " "), len(inside)
}

// TestWildGoldens_TheRuledTableCellsAgreeWithItsOwnTokens closes the seam between the two golden
// specs: AC-2 compares tokens against pdfium and AC-10b reads only the header row, so a
// hand-edited body cell is caught by the container step in CI and by nothing in Go.
//
// A cell is rebuilt from the tokens its own box contains, not required to BE one token: docling
// merges two tokens into one cell wherever a row prints two runs in the same column, which the
// ruled table's totals row now does. An invented, altered or reordered word still fails.
func TestWildGoldens_TheRuledTableCellsAgreeWithItsOwnTokens(t *testing.T) {
	pages := eeGoldenPages(t, wildGolden(wildRuled))

	tokens, cells, merged := 0, 0, 0
	for _, p := range pages {
		tokens += len(p.Tokens)
		for _, tbl := range p.Tables {
			for _, cell := range tbl.Cells {
				text := strings.TrimSpace(cell.Text)
				if text == "" {
					continue
				}
				cells++
				got, n := wildCellTokens(p, cell)
				if n > 1 {
					merged++
				}
				if got != text {
					t.Errorf("%s's cell (%d,%d) reads %q, but the %d token(s) inside its own box read %q; the golden was hand-edited", wildGolden(wildRuled), cell.Row, cell.Col, text, n, got)
				}
			}
		}
	}
	if cells == 0 || tokens == 0 {
		t.Fatalf("%s yielded %d table cell(s) and %d token(s); the comparison above held over nothing", wildGolden(wildRuled), cells, tokens)
	}
	// Floor: an all-single-token table would satisfy the rebuild for the weaker reason.
	if merged == 0 {
		t.Errorf("%s carries no multi-token cell; the rebuild above proves nothing a token-identity check did not", wildGolden(wildRuled))
	}
}

// TestWildGoldens_CarryRawUTF8AndNeverAnEscape is the property `ensure_ascii=False` exists for.
// Go's json.MarshalIndent writes raw UTF-8, so an escaped ₦ could never round-trip through
// TestWildGoldens_AreMachineGenerated -- but only after somebody regenerates. This reds on the
// committed bytes.
func TestWildGoldens_CarryRawUTF8AndNeverAnEscape(t *testing.T) {
	entries, err := os.ReadDir(eeFxDir)
	if err != nil {
		t.Fatalf("read %s: %v", eeFxDir, err)
	}
	nonASCII, scanned := 0, 0
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".docling.json") {
			continue
		}
		scanned++
		raw := eeFixtureBytes(t, e.Name())
		if strings.Contains(string(raw), `\u`) {
			t.Errorf("%s carries a \\u escape; the golden writer lost ensure_ascii=False and Go can never re-serialise it byte-for-byte", e.Name())
		}
		for _, b := range raw {
			if b > 0x7f {
				nonASCII++
				break
			}
		}
	}
	if scanned == 0 {
		t.Fatalf("%s holds no golden; the scan above asserts an absence and found nothing", eeFxDir)
	}
	// Floor: an all-ASCII corpus passes the escape clause for the wrong reason.
	if nonASCII == 0 {
		t.Errorf("no committed golden carries a non-ASCII byte; the naira arrangements are gone and this scan proves nothing about ensure_ascii=False")
	}
}

// --- the party block over the wild arrangements ----------------------------------------------

// Each party's TIN reaches its own field. This and TestWildLayouts_TheTwoPartyBuyerNameIsTheName
// together replaced the spec that pinned both readings as unfixed.
func TestWildLayouts_TheTwoPartyTINsBindToTheirOwnParty(t *testing.T) {
	supplierTIN, buyerTIN := wildTINs[0], wildTINs[1]

	supplier := wildResolved(t, wildTwoParty, "supplier_tin")
	if !slices.Contains(supplier, supplierTIN) {
		t.Errorf("%s: supplier_tin = %v, want it to hold %s; the label before the buyer heading falls back to the supplier", wildTwoParty, supplier, supplierTIN)
	}
	if slices.Contains(supplier, buyerTIN) {
		t.Errorf("%s: supplier_tin = %v and still holds the buyer's %s; a bare TIN under \"Invoice to\" is not the supplier's", wildTwoParty, supplier, buyerTIN)
	}

	buyer := wildResolved(t, wildTwoParty, "buyer_tin")
	if !slices.Contains(buyer, buyerTIN) {
		t.Errorf("%s: buyer_tin = %v, want it to hold %s", wildTwoParty, buyer, buyerTIN)
	}
	if slices.Contains(buyer, supplierTIN) {
		t.Errorf("%s: buyer_tin = %v and holds the supplier's %s; the heading owns only what follows it", wildTwoParty, buyer, supplierTIN)
	}
}

const (
	wildTwoPartyBuyerName = "Honeywell Group"
	wildTwoPartyHeading   = "Invoice to"
)

// The buyer's name on the two-party arrangement is the printed name, not the "Customer No." or
// "Buyer's Signature" fragment that used to outrank it.
//
// The list is not asserted to hold one value: "TIN:" survives at rank 1 as a pre-existing
// residue, and bare_tin matches it at [0,3] rather than whole, so nothing refuses it.
func TestWildLayouts_TheTwoPartyBuyerNameIsTheName(t *testing.T) {
	names := wildResolved(t, wildTwoParty, "buyer_name")

	if names[0] != wildTwoPartyBuyerName {
		t.Errorf("%s ranks buyer_name %v, want %q at rank 0; the label fragment still outranks the printed name", wildTwoParty, names, wildTwoPartyBuyerName)
	}
	for _, v := range names {
		if strings.Contains(v, "No.") || strings.Contains(v, "Signature") {
			t.Errorf("%s reaches %q as a buyer_name candidate (%v); a fragment of an owning phrase is a label, never a name", wildTwoParty, v, names)
		}
		// The heading is refused as a value at every rank, not only at rank 0: a candidate
		// list holding it is one tie-break away from writing a label into the invoice row.
		if v == wildTwoPartyHeading {
			t.Errorf("%s reaches its %q heading as a buyer_name candidate (%v); the label that introduces the name is not the name", wildTwoParty, wildTwoPartyHeading, names)
		}
	}

	// The control: the two party TINs on the same page. Without it the absence above holds
	// equally against a Resolve that stopped producing anything on this layout.
	supplierTIN, buyerTIN := wildTINs[0], wildTINs[1]
	if v := wildResolved(t, wildTwoParty, "supplier_tin"); !slices.Contains(v, supplierTIN) {
		t.Errorf("%s: supplier_tin = %v, want it to hold %s; the page still reads its other fields", wildTwoParty, v, supplierTIN)
	}
	if v := wildResolved(t, wildTwoParty, "buyer_tin"); !slices.Contains(v, buyerTIN) {
		t.Errorf("%s: buyer_tin = %v, want it to hold %s; the page still reads its other fields", wildTwoParty, v, buyerTIN)
	}
}

// --- AC-4: no layout loses a party name it already read ---------------------------------------

// wildPartyNameFields are the two fields the walk below compares. supplier_name has no key in
// expectByLayout at all -- it is an entityDerivedField and is excluded from the end-to-end
// score -- so the pinned table is the only oracle the supplier half has.
var wildPartyNameFields = []string{"supplier_name", "buyer_name"}

// wildPartyNames is the party name each layout reads at rank 0, measured through PDFium before
// the owning-phrase entries. A field a layout is not listed under read no name and is not
// compared: wild_two_party_bare_tin.pdf/buyer_name is absent on purpose (the baseline reads the
// "No." fragment, and replacing it is the point), corpus_totals_block.pdf and
// wild_stacked_borderless.pdf read no name at all, and wild_scanned_no_number.pdf yields no
// pdfium token -- its docling golden carries neither owning phrase.
var wildPartyNames = map[string]map[string]string{
	"corpus_inline_labels.pdf":    {"supplier_name": "Adeyemi Trading Limited", "buyer_name": "Honeywell Group"},
	"corpus_split_labels.pdf":     {"supplier_name": "Adeyemi Trading Limited", "buyer_name": "Honeywell Group"},
	"corpus_stacked_labels.pdf":   {"supplier_name": "Adeyemi Trading Limited", "buyer_name": "Honeywell Group"},
	"corpus_two_column.pdf":       {"supplier_name": "Adeyemi Trading Limited", "buyer_name": "Honeywell Group"},
	"corpus_ambiguous_date.pdf":   {"supplier_name": "Adeyemi Trading Limited"},
	"wild_ruled_lines_totals.pdf": {"supplier_name": "Adeyemi Trading Limited", "buyer_name": "Honeywell Group"},
	"wild_rc_due_naira.pdf":       {"supplier_name": "Adeyemi Trading Limited", "buyer_name": "Honeywell Group"},
}

const (
	wildPartyNameCells   = 13
	wildPartyNameLayouts = 11
)

// wildRank0Names is each field's rank-0 value over one layout under rules, or "" where the
// field produced no candidate.
func wildRank0Names(t *testing.T, layout string, rules []extraction.Tier1Rule) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, c := range extraction.Resolve(eeTokenPages(t, layout), extraction.RuleSet{Tier1: rules}) {
		if _, seen := out[c.Field]; !seen {
			out[c.Field] = c.Value
		}
	}
	return out
}

// wildPartyNameLosses counts the pinned cells rules fails to reproduce.
func wildPartyNameLosses(t *testing.T, rules []extraction.Tier1Rule) (losses, compared int, report []string) {
	t.Helper()
	for _, want := range expectByLayout {
		got := wildRank0Names(t, want.file, rules)
		for _, field := range wildPartyNameFields {
			pinned, ok := wildPartyNames[want.file][field]
			if !ok {
				continue
			}
			compared++
			if got[field] != pinned {
				losses++
				report = append(report, want.file+"/"+field+" reads "+got[field]+", want "+pinned)
			}
		}
	}
	return losses, compared, report
}

func TestPartyNames_NoLayoutLosesAPartyNameItAlreadyRead(t *testing.T) {
	if len(expectByLayout) != wildPartyNameLayouts {
		t.Fatalf("expectByLayout names %d layout(s), want %d; the walk below would cover a different corpus than the table was measured on", len(expectByLayout), wildPartyNameLayouts)
	}
	for layout := range wildPartyNames {
		if !slices.ContainsFunc(expectByLayout, func(r struct {
			file   string
			fields map[string][]string
		}) bool {
			return r.file == layout
		}) {
			t.Fatalf("wildPartyNames pins %s, which expectByLayout does not name; the walk would skip that row in silence", layout)
		}
	}

	losses, compared, report := wildPartyNameLosses(t, extraction.Tier1Rules)
	if compared != wildPartyNameCells {
		t.Fatalf("compared %d party-name cell(s), want %d; the table shrank and the assertion below covers that much less", compared, wildPartyNameCells)
	}
	for _, line := range report {
		t.Errorf("%s; a layout lost a party name the baseline already read", line)
	}

	// The control needle: the same walk with every buyer_name rule dropped must LOSE cells, or
	// the comparison above would report clean against a Resolve that reads no name at all.
	var cut []extraction.Tier1Rule
	for _, r := range extraction.Tier1Rules {
		if r.Field != "buyer_name" {
			cut = append(cut, r)
		}
	}
	if len(cut) == len(extraction.Tier1Rules) {
		t.Fatal("the control cut dropped no rule; it is not the needle it claims to be")
	}
	if cutLosses, _, _ := wildPartyNameLosses(t, cut); cutLosses == 0 {
		t.Errorf("dropping every buyer_name rule cost %d pinned cell(s) and the shipped set cost %d; the comparison is inert", cutLosses, losses)
	}
}

// --- the print arm of the owning-phrase exemption ---------------------------------------------

const (
	wildPrintedPhraseFile = "../tier1_internal_test.go"
	wildPrintedPhraseDecl = "var t1PrintedPhraseIDs = "

	// wildPrintedPhraseFloor is a label every shipped layout set carries many times over. This
	// spec asserts a PRESENCE, so a walk that observed nothing must fail on the floor first.
	wildPrintedPhraseFloor = "invoice_no"
)

// wildUnprintedPhraseIDs are shipped lexicon ids no layout prints. They are the needle that keeps
// the declared set derived from what the documents carry rather than from the lexicon.
var wildUnprintedPhraseIDs = []string{"reg_identifier", "doc_title"}

var wildPrintedPhraseID = regexp.MustCompile(`"([a-z_]+)"`)

// An owning phrase no rule-bearing entry sits inside suppresses nothing, so containment cannot be
// why it ships. It earns its place by being printed. This is the other arm of
// TestAnchorLexicon_AnOwningPhraseEarnsItsExemption, which cannot read a PDF.
func TestWildLayouts_APrintedOwningPhraseIsObservedOnTheCorpus(t *testing.T) {
	body := wildVarBody(t, wildReadFile(t, wildPrintedPhraseFile), wildPrintedPhraseDecl, wildPrintedPhraseFile)
	var declared []string
	for _, m := range wildPrintedPhraseID.FindAllStringSubmatch(body, -1) {
		declared = append(declared, m[1])
	}
	if len(declared) == 0 {
		t.Fatalf("%s's %q names no id; the walk below would assert nothing", wildPrintedPhraseFile, wildPrintedPhraseDecl)
	}
	if len(expectByLayout) != wildPartyNameLayouts {
		t.Fatalf("expectByLayout names %d layout(s), want %d; the walk below would cover a different corpus", len(expectByLayout), wildPartyNameLayouts)
	}

	observed := map[string][]string{}
	for _, want := range expectByLayout {
		for _, o := range extraction.AnchorObservations(eeTokenPages(t, want.file)) {
			observed[o.Label] = append(observed[o.Label], want.file)
		}
	}
	if len(observed[wildPrintedPhraseFloor]) == 0 {
		t.Fatalf("no shipped layout observed %s; the walk is not reading the corpus and every id below would read unprinted", wildPrintedPhraseFloor)
	}

	for _, id := range declared {
		if len(observed[id]) == 0 {
			t.Errorf("no shipped layout prints %s; an owning phrase that suppresses nothing and appears nowhere ships in the fingerprint and does nothing", id)
		}
	}
	for _, id := range wildUnprintedPhraseIDs {
		if len(observed[id]) != 0 {
			t.Errorf("%s is observed on %v, so the corpus does print it; the declared set must be what the documents carry, not what the lexicon holds", id, observed[id])
		}
	}
}

// The arm above takes any layout. This names the token behind the one rc_number observation the
// corpus carries, so the arm cannot come to rest on some other document's phrase.
func TestWildLayouts_TheRCLineIsTheOnlyCompanyNumberLabelTheCorpusPrints(t *testing.T) {
	const printed = "RC NUMBER: " + wildRCNumber
	pages := eeTokenPages(t, wildRCNaira)

	found := false
	for _, p := range pages {
		for _, tok := range p.Tokens {
			if tok.Text == printed {
				found = true
			}
		}
	}
	if !found {
		t.Fatalf("%s prints no %q token; the label hit asserted below would be a hit on some other text", wildRCNaira, printed)
	}

	var hits []string
	for _, o := range extraction.AnchorObservations(pages) {
		if o.Label == "rc_number" {
			hits = append(hits, o.Text)
		}
	}
	if !slices.Equal(hits, []string{"RC NUMBER"}) {
		t.Errorf("%s observes rc_number as %v, want exactly [RC NUMBER]; the printed line must be a label hit, and the value behind the colon must stay outside it", wildRCNaira, hits)
	}
}

// The scanned layout has no text layer, so its tokens come from the committed golden. The
// Tier-1 binding is fixed here even though the cell still misses end to end -- the document
// quarantines and writes no invoices row.
func TestRLS_EndToEndTheScannedLayoutBindsTheBuyerTIN(t *testing.T) {
	supplierTIN, buyerTIN := wildTINs[8], wildTINs[9]

	var pages []extraction.TokenPage
	r := eeGoldenReader(t, wildGolden(wildScanned))
	if _, err := r.Read(t.Context(), extraction.Document{ContentType: eeContentType}, extraction.CollectTokens(&pages)); err != nil {
		t.Fatalf("replay the %s golden: %v", wildScanned, err)
	}
	if len(pages) == 0 {
		t.Fatalf("the %s golden replayed 0 page(s); everything resolved below is resolved from nothing", wildScanned)
	}

	got := map[string][]string{}
	for _, c := range extraction.Resolve(pages, extraction.RuleSet{Tier1: extraction.Tier1Rules}) {
		got[c.Field] = append(got[c.Field], c.Value)
	}
	if len(got) == 0 {
		t.Fatalf("the %s golden's tokens produced no candidate at all; every assertion below would hold over nothing", wildScanned)
	}

	if !slices.Contains(got["buyer_tin"], buyerTIN) {
		t.Errorf("%s: buyer_tin = %v, want it to hold %s; the bare TIN follows the BILL TO: heading", wildScanned, got["buyer_tin"], buyerTIN)
	}
	if slices.Contains(got["supplier_tin"], buyerTIN) {
		t.Errorf("%s: supplier_tin = %v and still holds the buyer's %s", wildScanned, got["supplier_tin"], buyerTIN)
	}
	if !slices.Contains(got["supplier_tin"], supplierTIN) {
		t.Errorf("%s: supplier_tin = %v, want it to hold %s; without it the exclusion above holds against a field nothing reaches", wildScanned, got["supplier_tin"], supplierTIN)
	}
}
